# Generated by Django 4.1.3 on 2022-12-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='fec_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
